
insert into MinistrySort values ('NON-MINISTRY DEPARTMENTS', 10);
insert into MinistrySort values ('CABINET OFFICE DEPARTMENTS', 20);
insert into MinistrySort values ('MINISTRY OF JUSTICE', 30);
insert into MinistrySort values ('MINISTRY OF LEGAL AFFAIRS', 30);
insert into MinistrySort values ('MINISTRY OF LEGISLATIVE AFFAIRS', 30);
insert into MinistrySort values ('MINISTRY OF LEGAL AFFAIRS & CONSTITUTIONAL REFORM', 30    );
insert into MinistrySort values ('MINISTRY OF FINANCE ', 50);
insert into MinistrySort values ('MINISTRY OF EDUCATION ', 60);
insert into MinistrySort values ('MINISTRY OF EDUCATION & DEVELOPMENT', 60);
insert into MinistrySort values ('MINISTRY OF EDUCATION & ECONOMIC DEVELOPMENT', 60);
insert into MinistrySort values ('MINISTRY OF EDUCATION & WORKFORCE DEVELOPMENT', 60);
insert into MinistrySort values ('MINISTRY OF EDUCATION, SPORTS & RECREATION', 60);
insert into MinistrySort values ('MINISTRY OF YOUTH, FAMILIES, SPORTS & COMMUNITY DEVELOPMENT', 60);
insert into MinistrySort values ('MINISTRY OF HEALTH', 70);
insert into MinistrySort values ('MINISTRY OF HEALTH & ENVIRONMENT', 70);
insert into MinistrySort values ('MINISTRY OF HEALTH & FAMILY SERVICES', 70);
insert into MinistrySort values ('MINISTRY OF HEALTH & SENIORS', 70);
insert into MinistrySort values ('MINISTRY OF HEALTH, SENIORS & ENVIRONMENT', 70);
insert into MinistrySort values ('MINISTRY OF ENVIRONMENT & PLANNING', 75);
insert into MinistrySort values ('MINISTRY OF ENVIRONMENT, PLANNING & INFRASTRUCTURE STRATEGY', 75);
insert into MinistrySort values ('MINISTRY OF THE ENVIRONMENT', 75);
insert into MinistrySort values ('MINISTRY OF THE ENVIRONMENT & SPORT', 75);
insert into MinistrySort values ('MINISTRY OF THE ENVIRONMENT & SPORTS', 75);
insert into MinistrySort values ('MINISTRY OF THE ENVIRONMENT, TELECOMMUNICATIONS & E-COMMERCE', 75);
insert into MinistrySort values ('MINISTRY OF LABOUR', 80);
insert into MinistrySort values ('MINISTRY OF LABOUR & IMMIGRATION', 80);
insert into MinistrySort values ('MINISTRY OF LABOUR, COMMUNITY AFFAIRS & SPORTS', 80);
insert into MinistrySort values ('MINISTRY OF LABOUR, HOME AFFAIRS & HOUSING', 80);
insert into MinistrySort values ('MINISTRY OF LABOUR, HOME AFFAIRS & PUBLIC SAFETY', 80);
insert into MinistrySort values ('MINISTRY ECONOMY, TRADE & INDUSTRY', 90);
insert into MinistrySort values ('MINISTRY OF BUSINESS DEVELOPMENT & TOURISM', 90);
insert into MinistrySort values ('MINISTRY OF ECONOMIC DEVELOPMENT', 90);
insert into MinistrySort values ('MINISTRY OF ECONOMIC DEVELOPMENT & TOURISM', 90);
insert into MinistrySort values ('MINISTRY OF ECONOMY & LABOUR', 90);
insert into MinistrySort values ('MINISTRY OF ECONOMY, TRADE & INDUSTRY', 90);
insert into MinistrySort values ('MINISTRY OF TRANSPORT', 100);
insert into MinistrySort values ('MINISTRY OF TRANSPORT & REGULATORY AFFAIRS', 100);
insert into MinistrySort values ('MINISTRY OF TOURISM, TELECOMMUNICATIONS & E-COMMERCE', 105);
insert into MinistrySort values ('MINISTRY OF TOURISM, TRANSPORT & MUNICIPALITIES', 105);
insert into MinistrySort values ('MINISTRY OF TOURISM & TRANSPORT', 110);
insert into MinistrySort values ('MINISTRY OF TOURISM DEVELOPMENT & TRANSPORT', 110);
insert into MinistrySort values ('MINISTRY OF HOUSING', 120);
insert into MinistrySort values ('MINISTRY OF PUBLIC WORKS', 120);
insert into MinistrySort values ('MINISTRY OF WORKS & ENGINEERING', 120);
insert into MinistrySort values ('MINISTRY OF WORKS & ENGINEERING & HOUSING', 120);
insert into MinistrySort values ('MINISTRY OF GOVERNMENT ESTATES & INFORMATION SERVICES', 125);
insert into MinistrySort values ('MINISTRY OF COMMUNITY & CULTURAL AFFAIRS', 130);
insert into MinistrySort values ('MINISTRY OF COMMUNITY & CULTURAL DEVELOPMENT', 130);
insert into MinistrySort values ('MINISTRY OF COMMUNITY AFFAIRS & SPORT', 130);
insert into MinistrySort values ('MINISTRY OF COMMUNITY, CULTURE & SPORTS', 130);
insert into MinistrySort values ('MINISTRY OF CULTURE & SOCIAL REHABILITATION', 130);
insert into MinistrySort values ('MINISTRY OF SOCIAL DEVELOPMENT & SPORTS', 130);
insert into MinistrySort values ('MINISTRY OF YOUTH, CULTURE & SPORTS', 130);
insert into MinistrySort values ('MINISTRY OF YOUTH, FAMILIES & SPORTS', 130);
insert into MinistrySort values ('MINISTRY OF NATIONAL SECURITY', 150);
insert into MinistrySort values ('MINISTRY OF SOCIAL DEVELOPMENT & SENIORS', 160);
insert into MinistrySort values ('MINISTRY OF SOCIAL REHABILITATION', 160);
insert into MinistrySort values ('MINISTRY OF PUBLIC INFORMATION SERVICES', 170);
insert into MinistrySort values ('MINISTRY OF ENERGY, TELECOMMUNICATIONS & E-COMMERCE', 170);
insert into MinistrySort values ('MINISTRY OF HOME AFFAIRS', 170);
insert into MinistrySort values ('MINISTRY OF PUBLIC SAFETY', 170);
insert into MinistrySort values ('MINISTRY OF PUBLIC SAFETY & HOUSING', 170);
insert into MinistrySort values ('MINISTRY OF TELECOMMUNICATIONS & E-COMMERCE', 170);
