insert into ExpenseAnalysisGroup values ('Advertising & Printing', 'ADVERTISING & PROMOTION');
insert into ExpenseAnalysisGroup values ('Advertising & Printing', 'PRINTING, STATIONERY & ADVERTISING');
insert into ExpenseAnalysisGroup values ('Communications', 'COMMUNICATIONS');
insert into ExpenseAnalysisGroup values ('Communications', 'POSTAGE, CABLES & PHONE');
insert into ExpenseAnalysisGroup values ('Debt Cost', 'PUBLIC DEBT CHARGES');
insert into ExpenseAnalysisGroup values ('Energy', 'ELECTRICITY');
insert into ExpenseAnalysisGroup values ('Energy', 'ENERGY');
insert into ExpenseAnalysisGroup values ('Energy', 'FUEL');
insert into ExpenseAnalysisGroup values ('Grants', 'GRANTS & CONTRIBUTIONS');
insert into ExpenseAnalysisGroup values ('Materials, Supplies & Eqpt.', 'CLOTHING & UNIFORMS');
insert into ExpenseAnalysisGroup values ('Materials, Supplies & Eqpt.', 'EQUIPMENT');
insert into ExpenseAnalysisGroup values ('Materials, Supplies & Eqpt.', 'MATERIALS & SUPPLIES');
insert into ExpenseAnalysisGroup values ('Materials, Supplies & Eqpt.', 'OPERATIONAL MATERIALS & SUPPLIES');
insert into ExpenseAnalysisGroup values ('Other', 'CAPITAL RECHARGES');
insert into ExpenseAnalysisGroup values ('Other', 'DEPARTMENTAL SUPPORT');
insert into ExpenseAnalysisGroup values ('Other', 'INSURANCE');
insert into ExpenseAnalysisGroup values ('Other', 'MIN. OF FINANCE INVESTIGATIONS');
insert into ExpenseAnalysisGroup values ('Other', 'MISCELLANEOUS');
insert into ExpenseAnalysisGroup values ('Other', 'OTHER EXPENSES');
insert into ExpenseAnalysisGroup values ('Other', 'RECEIPTS CREDITED TO PROGRAMME');
insert into ExpenseAnalysisGroup values ('Other', 'RESERVE FUNDS');
insert into ExpenseAnalysisGroup values ('Other', 'SPECIAL EXPENDITURE');
insert into ExpenseAnalysisGroup values ('Other', 'TRAINING');
insert into ExpenseAnalysisGroup values ('Other', 'TRANSFER TO OTHER FUNDS');
insert into ExpenseAnalysisGroup values ('Other', 'W & E DEPARTMENTAL SUPPORT');
insert into ExpenseAnalysisGroup values ('Prof. Services', 'PROFESSIONAL SERVICES');
insert into ExpenseAnalysisGroup values ('Rentals', 'RENTALS');
insert into ExpenseAnalysisGroup values ('Repairs & Maint.', 'REPAIR & MAINTENANCE');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'EMPLOYER OVERHEAD');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'MEMBERS PENSIONS');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'OTHER PERSONNEL COSTS');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'OVERTIME');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'SALARIES');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'SUPERANNUATION & PENSION');
insert into ExpenseAnalysisGroup values ('Staff Costs', 'WAGES');
insert into ExpenseAnalysisGroup values ('Transport/Travel', 'TRANSPORT');
insert into ExpenseAnalysisGroup values ('Transport/Travel', 'TRANSPORT & TRAVEL');
insert into ExpenseAnalysisGroup values ('Transport/Travel', 'TRAVEL');